### ISSUE TITLE
Hmac API key removes itself after regeneration

### ISSUE THREAD

**Issue by dimitri-ak** [VirtoCommerce/vc-platform#1100]
Version info: 
- Browser version: Chrome 60
- Platform version: 2.13.11

### Expected behavior
Should change API key
### Actual behavior
Hmac API key removes itself after regeneration
### Steps to reproduce
1. Create new HMac key
2. Click Save button
3. Under API keys got 1 API keys
4. Generate new HMac key for created key
5. Click Save button
6. Under API keys got 0 API keys

**Comment by asvishnyakov** [comment]
Research:
UI implementation is different from backend implmenetation. The differences is:
1. API Key is really API account. It's important to describe entities from "API Keys" widget as API accounts to not be confused with real API keys (long numbers)
1. ApiAccountType and AppId is real & unique identifiers for API account
2. Simple api account `Key` is really `AppId` in backend
So from this follows the consequences:
1. We must change "API key" name in UI to "API account"
2. We can choose API account type only at creation, because ApiAccountType is part of it's unique identifier
3. We must show "Generate" button only for Hmac accounts, because Simple account has no secret keys, only AppID.

**Comment by asvishnyakov** [comment]
New Hmac api account created:
![screenshot 324](https://user-images.githubusercontent.com/6369252/28930718-4a5247fa-788d-11e7-928a-821c7342a707.png)
After save:
![screenshot 325](https://user-images.githubusercontent.com/6369252/28930719-4a764c9a-788d-11e7-9afb-bfff265faa73.png)
You can choose account type only for new key:
![screenshot 326](https://user-images.githubusercontent.com/6369252/28930720-4a81668e-788d-11e7-9510-cdf787c09e3b.png)
Simple account `Key` renamed to `App ID`
![screenshot 327](https://user-images.githubusercontent.com/6369252/28930721-4a87e23e-788d-11e7-9b40-c661be3ae34d.png)
