### ISSUE TITLE
Accounts should have a setting to disable lockout

### ISSUE THREAD

**Issue by Skrypt** [VirtoCommerce/vc-platform#1129]
We sometimes have customers that tries to login with their account because they forgot their password. When we receive a call from those customers it would be great to be able to disable the lockout on their account simply from the admin UI. Right now we need to wait for the lockout to expire which I think is 5 minutes.

**Comment by tatarincev** [comment]
User lock-unlock UI improvements:
Instead of using command in toolbar for unlocking user I'm would to suggest use checkbox for this operation. And also instead of using separate API methods for locking/unlocking I would to suggest include this state in user model and change it state within single update operation.
image

**Comment by artem-dudarev** [comment]
There is no 'lock' operation, only unlock. Therefore the checkbox will be confusing.
