### ISSUE TITLE
GetNewNotificaiton(string type) should return notification with body/subject filled?

### ISSUE THREAD

**Issue by danielstarzewski** [VirtoCommerce/vc-platform#1197]
Hello,

Please let me know what should be the expected result from the operation described below as I believe current behavior is on the border of being a bug

Version info: 
- Platform version: 2.13.15

### Steps to reproduce
1. For given template type create template for 'en-US' language. Fill it with subject and/or body.
2. Create a new notification programatically using GetNewNotificaiton(string type) from NotificationManager class. Please note this overload does not require language as a parameter. 
 
In result I receive a new notification but it doesn't have body/subject filled with the data I saved previously. I belive this is because of the null langugae parameter (when I pass 'en-US' I receive data as expected). 
What should be the desired behavior in this case? When should I use GetNewNotification(string type) method? Also what is the purpose of objectId and objectTypeId? When should I use them?

Thank you in advance,
Daniel

**Comment by tatarincev** [comment]
Please use this method `INotificationManager.GetNewNotification<T>(string objectId, string objectType, string language)` instead of `GetNewNotificaiton<T>()`.

The thing is, each notification can have templates that can be defined for a particular object, that is, they are limited by the scope (i.e store),  and formal parameters **ObjectId** and **ObjectType** are identifiers of this object (ObjectId = 'Electronics', ObjectType = 'Store').  

Calling this method
`INotificationManager.GetNewNotification<MyNotification>( "Electronics","Store", "en-US")` 
will return notification with template belongs to store with id = 'Electronics'. Store -> Notifications widget.
Although calling this method
`INotificationManager.GetNewNotification<MyNotification>( "Electronics","Store", "en-US")` 
will return notification with globaly defined (Menu -> Notifications) template. 

A good example how to work with notifications, you can find here
https://github.com/VirtoCommerce/vc-module-order/blob/master/VirtoCommerce.OrderModule.Data/Observers/OrderNotificationObserver.cs#L51
