### ISSUE TITLE
Improve modules auto installation

### ISSUE THREAD

**Issue by dimitri-ak** [VirtoCommerce/vc-platform#1262]
Add to current app setting "VirtoCommerce:AutoInstallModuleBundles" option to specify module to install by module Id.

**Comment by tatarincev** [comment]
I suggest another way to reach desired `selective` installation behavior. 
Due to the fact that the application setting `VirtoCommerce:AutoInstallModuleBundles`  supports multiple bundles (comma separated) you can set all the groups that you want there. And then you only need to add the desired group to the modules manifests in  the [modules.json](https://github.com/VirtoCommerce/vc-modules/blob/master/modules.json) file

**Comment by artem-dudarev** [comment]
@tatarincev Users cannot change the content of modules.json, but they can configure appSettings in their environment, and list every module they want to be installed automatically.
