### ISSUE TITLE
Admin site failed to start

### ISSUE THREAD

**Issue by dimitri-ak** [VirtoCommerce/vc-platform#1334]
Version info: 
- Browser version: any
- Platform version: 2.13.19

Prerequisites: 2 azure web apps with redis cache

Getting the following:
![image](https://user-images.githubusercontent.com/7642075/39857401-84da15d8-5433-11e8-9b32-7fc8020e51f1.png)

**Comment by tatarincev** [comment]
Could you try on the latest version, because in   [2.13.24](https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.24 ) versions there was a fix of this issue 
There is commit which related to this issue
https://github.com/VirtoCommerce/vc-platform/commit/ceb2517b85396b97b71ca627ea2cd740c758161a

**Comment by dimitri-ak** [comment]
Issue is not fixed.
The same thing we have on platform 2.13.27.
I am not sure that you add StrongName DLL to packages.config and project file.
FYI StrongName DLL is required when you are running platform in Azure with Redis Cache, because this environment is considered as secured.

**Comment by tatarincev** [comment]
https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.28
