### ISSUE TITLE
Occur error when adding my module

### ISSUE THREAD

**Issue by MaryamHsn** [VirtoCommerce/vc-platform#1341]
Version info: 
Browser version: any
Platform version: 2.13.26

when i create my own module according this document 
[https://virtocommerce.com/docs/vc2devguide/working-with-platform-manager/extending-functionality/creating-new-module](url)
it works and i can see it in [http://localhost/admin/docs/ui/index](url)
 but when i create my second module i have error 404 and i can't see my first and second module in [http://localhost/admin/docs/ui/index](url).
![screenshot 9](https://user-images.githubusercontent.com/34409766/40883845-c22416c8-671b-11e8-88fa-12735d9a269a.png)

I expect add more than oe module

@n2pro

**Comment by n2pro** [comment]
@MaryamHsn can attach these modules for debugging?

**Comment by MaryamHsn** [comment]
https://files.fm/u/tyjcaymz



@n2pro

**Comment by n2pro** [comment]
@MaryamHsn  OK, I will take a look

**Comment by MaryamHsn** [comment]
Thank you.  I look forward to your comment. 
@n2pro

**Comment by n2pro** [comment]
@MaryamHsn The problem is that the name of the controllers must be individual. Now you have two modules with the same controller names  **ManagedModuleController**: ApiController.

1. Remove the custom modules (TestModule1, TestModule2 and other custom) from the \VirtoCommerce.Platform.Web\Modules
2. Delete all files from the \VirtoCommerce.Platform.Web\App_Data\Modules
3. iisreset
4. Install TestModule1
5. Must be all good
![screenshot_2](https://user-images.githubusercontent.com/13115017/41344419-5af6b5b2-6f01-11e8-91e2-b18e065ac02e.png)
