### ISSUE TITLE
Category cannot be opened after the search in Catalog

### ISSUE THREAD

**Issue by mvsmal** [VirtoCommerce/vc-platform#1512]
**Describe the bug**
If you search in Catalog for a category and click on it in the results, it won't open.

**Steps to reproduce**
1. In the menu go to Catalog
2. Search for an existing category ("eyebolts" on demo)
3. Click on the found __Eyebolts__ category
4. A new blade is opened and closed immediately

**Expected behavior**
The list of underlying items is shown

**Screenshots (optional)**
The first example shows everything ok because the category is chosen manually from the catalog "Bolts".
The second example shows an attempt to open a found category.
![category_blade](https://user-images.githubusercontent.com/3872761/51391104-77470000-1b31-11e9-91b6-22b2cac78752.gif)

**Version info (please complete the following information):**
 - Browser version: Google Chrome 71.0.3578.98
 - Platform version: https://admin-demo.virtocommerce.com (2.13.40)

**Additional context (optional)**

**Comment by ilyawzrd** [comment]
The problem is with the category of "Bolts" (in the search results there are folders and their content at the same time, so when we try to open folders, this behavior happens(it's how i understand it)). In other categories, the search works correctly and as a result the folders do not fall out, but only their content is visible. Therefore, I have a question: if the script works with all the other categories normally, can there be a problem in the data itself?

**Comment by mvsmal** [comment]
@ilyawzrd Probably, I explained incorrectly.

The issue happens only when you search in _any_ catalog for _any_ category. It doesn't matter if the results contain both categories and items or just categories. For example, you can search for "Headphones" in "Electronics" catalog. Only one category will appear in the search results and you won't be able to open it.

Categories can be opened only without searching (by just clicking through catalog and categories).
