### ISSUE TITLE
Extending another entity with asset

### ISSUE THREAD

**Issue by pixellos** [VirtoCommerce/vc-platform#1569]
Hi,

We did tried to extend `CategoryAsset` with assets, using `IHasAssets` and we cannot simply extend this table with `CategoryId` because there is required FK for `Item` (`ItemId`)

We do want to handle assets on category, is that possible somehow?

**Comment by yecli** [comment]
Probably adding columns to existing table is not the best way to achieve this, as it could be changed in platform module future versions. 
In your extension you could add your table e.g. CategoryAsset, add mappings for [as in `CatalogAssets`](https://github.com/VirtoCommerce/vc-module-catalog/blob/aaac917256e9033d7247e04130a6130bfec10b77/VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs#L118-L121) and add these assets to `CategoryEntity` [like in `ItemEntity`](https://github.com/VirtoCommerce/vc-module-catalog/blob/56fb799d45172b35446d5b3268af8107b8bfcffc/VirtoCommerce.CatalogModule.Data/Model/ItemEntity.cs#L92).
What for `IHasAssets` - it is for model, you could make your own [`Category`](https://github.com/VirtoCommerce/vc-module-core/blob/025ae6e5722f49033899122994c9a65aad22d5fe/VirtoCommerce.Domain/Catalog/Model/Category.cs#L7) subclass with `IHasAssets` implementation, and register it instead of `Category` in our `AbstractTypeFactory` ([sample for pricing module](https://github.com/VirtoCommerce/vc-samples/blob/master/External.PriceModule/External.PriceModule.Web/Module.cs#L46-L47)).

There is a specific detail for Catalog module - it has web models together with domain ones. Now web model filling for `Category` is not extendable, that requires changes in vc-module-catalog.
I think we could add these extension points, after that extending `Category` would be possible.

Here is the [question on SO](https://github.com/VirtoCommerce/vc-platform/issues/1569) about Product extension - probably it could be useful.

**Comment by yecli** [comment]
After discussion we decided to add Assets support for Categories on platform level.
Catalog module extensions model will not be improved here because it is already reworked in platform v3.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-97
