### ISSUE TITLE
New Storefront - Searh bar is showing "404 Page Not Found" Error

### ISSUE THREAD

**Issue by anwaramoon** [VirtoCommerce/vc-platform#165]
Steps
1. Enter any product name or category name and enter search. 

<img width="1107" alt="search_bar_404_error" src="https://cloud.githubusercontent.com/assets/1743538/11755064/9c8bd600-a047-11e5-8b52-2d67a9ae14f3.PNG">

Is this something work in-progress or a bug?

Thanks

**Comment by Woland2k** [comment]
If it is storefront branch, then it is still work in progress. I would also try accessing "http://storefront/electronics" instead of clothing store as it seems to have a bit more working functionality.  We currently working on connecting dynamics content, search/filters to that new storefront. Some new functionality you might want to checkout is actually in the "checkout" page (completely angularjs based and much more dynamic/untuitive).

**Comment by anwaramoon** [comment]
Thanks @Woland2k 

I have also tried on electronics store but same result. It could be something work in-progress than. I'll wait for above changes to be completed. However, new storefront is looking great. Keep up the good work.

<img width="1012" alt="search_bar_404_error_electronics" src="https://cloud.githubusercontent.com/assets/1743538/11758115/5276ac94-a05f-11e5-81cc-6b43960fd425.PNG">

**Comment by IgorisB** [comment]
It seems issue is solved. Please reopen if it still doesn't work for you.
