### ISSUE TITLE
Unable to generate a high count of marketing promotion coupons

### ISSUE THREAD

**Issue by emathavan** [VirtoCommerce/vc-platform#1775]
When we try to generate 10,000 coupons and call the CouponService SaveCoupon method and pass in the list of coupons, it takes a long to to save to the database and times out and we never get to the point of being able to download the generated file.

Are there known limitations to the number of coupons that can be generated, and, if so, is there a fix coming in the near future?

Load the Admin Application
Got to Admin > Marketing > Promotions
Select promotion with existing coupons
Click "Coupons" tile
Select "Export" on the toolbar
Click "Start export"

Generating 1000 coupons seems to work fine but generating 10000 coupons seems to always timeout.  Ability to generate and export 10,000 coupons should work.

We are using VirtoCommerce.Domain version 2.25.32 and version 2.17.8 of the marketing module vc-module-marketing.

![image](https://user-images.githubusercontent.com/37384557/73139778-85cad000-403f-11ea-8e90-78f8203e3065.png)

**Comment by yecli** [comment]
@emathavan 
Regarding your initial question about CouponService SaveCoupon limitations - there are no defined strict limitations for the saving. It is reasonable that saving a lot (e.g. 10k) coupons will take a lot of time because the EF data context would have a lot of changes in that case. For large data volumes the common practice is to read/save data in batches (batch size can be set individually based on the experiment):
https://github.com/VirtoCommerce/vc-module-order/blob/dev/VirtoCommerce.OrderModule.Web/ExportImport/OrderExportImport.cs#L46

Seems "Export" and "Generate" abilities are not part of standard marketing module functionality. So we do not have control over them. I strongly recommend your team using the batch handling in these functions.

**Comment by emathavan** [comment]
Ok, thanks for the quick response
