### ISSUE TITLE
Variation of product not working as expected.

### ISSUE THREAD

**Issue by shubhamdhanetia** [VirtoCommerce/vc-platform#2110]
I have created a variation of a digital product, and then in the storefront, selected the variation property on the product page.
Then only the image of the product gets changed after selecting the variance property.
The description remains the same and also the Add to Cart button is disabled for the variation object automatically.
I have tried this on two products and both times, the issue occurred.

In the first image, the original product is shown. In the next image, a variation product is shown after clicking on the variance property.
And the add to cart button disappeared and also the description is not changed according to the variation product

![image](https://user-images.githubusercontent.com/71070755/101080175-73f67980-35ce-11eb-9dc6-e5aecb4cd4e8.png)

![image](https://user-images.githubusercontent.com/71070755/101080212-7f49a500-35ce-11eb-9763-24df11b56ff2.png)

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-6325 has been created

**Comment by yecli** [comment]
Hi @shubhamdhanetia.

About the question with changing description when switching to variation - it is by design - we are using main product description in our theme. It could be customized on the theme level.
Cannot reproduce Add to cart button problem.

You could ask and discuss questions on our community page: https://www.virtocommerce.org/
Also, you could use our support service, in case you have a license - https://help.virtocommerce.com/support/home.
