### ISSUE TITLE
Bundles, Packages and product grouping feature

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#289]
- Manager can configure bundles with exists products which can't will be selling individually.
- Manager can assign price for each bundle
- Bundles displayed in storefront as single product but customer can see all the products of which it consists.
- Customer can add to shopping cart only whole bundle and cannot add product from bundle separately

**Comment by dungle** [comment]
Thanks for creating a ticket for this.

What we need is to set based price for all item, because we are not selling them separately. Let say, all items have same based price (or no price at all). Then we would have a configuration where we configure price based on number of items in shopping cart.
- up to 3 items: total prices is 100$ (configurable)
- up to 6 items: total prices is 200$

So we would need to configure step before jump to next price level. In this example is every 3 items will make new price (100$ jump step).

Hope I make it clear enough.

**Comment by esbee** [comment]
Product kits/bundle are a very important feature. 

It would be great to be able to group separate individual products into 1 product kit with overridable name, price, pictures, description, etc. and to leave an option whether the products can be sold individually or not.

For example:

Listed products:
- Product A $10 (option CanBeSoldIndividually=true, will appear in the catalog)
- Product B $12 (option CanBeSoldIndividually=false, will not appear in the catalog)
- Product kit AB (2x Product A + 1x product B) $29 (overriden price) instead of $32 (calculated price)

**Comment by HtrBr** [comment]
Product Bundle are a very important feature.

What we need is ....

Product A + Product B + Product C for Set price X which is a discounted price and lower then the individual product prices.

**Comment by Skrypt** [comment]
We did product configurations here by using product variations and product associations features in Virto. Though it is all custom made.

**Comment by zhangpengchen** [comment]
It's an important feature, and was there in 1.x.
VirtoCommerce is API driven, allow back-end to support product kits/bundle setup is more important than start implementing in storefront. I don't know if this will save some time.

**Comment by asvishnyakov** [comment]
@tatarincev @Woland2k Check status please

**Comment by tatarincev** [comment]
This feature request has been added to the internal product backlog.

**Comment by benb1n** [comment]
@tatarincev Is this feature still being considered? I just had a customer ask about it.
