### ISSUE TITLE
Module which auto filled promotion, prices evaluation context by Geo IP databases

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#456]
https://www.maxmind.com/en/geoip2-services-and-databases

**Comment by attilah** [comment]
Since default to MaxMind is a good thing IMHO, I've used their DB previously.

http://dev.maxmind.com/geoip/geoip2/geolite2/

I think the license permits to include the free database with VC, or this licensing behavior can be offloaded to the user by writing good documentation for this module.

Going with City level support I think is a good starter.

What need to be made sure is that you've somehow that is it a paid database what is in use or the free. Since in the payed version a lot of other property can be populated into the eval context.

Geo Coordinates, Continent, Country, City is simple and a good starter with the free db.

I suggest to implement it by using their binary db, don't import their CSV.

**Comment by Woland2k** [comment]
It also might be good to use javascript based geolocation instead of IP based to figure out customer location. It becomes more and more acceptable to ask user permission.

**Comment by attilah** [comment]
No, plz no. yes it needs to be declared in the privacy policy, but since you add at least one analytic service to your website, you have to do it anyway.

JS is client side and such info can not be trusted ;-) I don't have to emphasize this ;-)

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog.
