### ISSUE TITLE
Shopify theme installation fails

### ISSUE THREAD

**Issue by amironoff** [VirtoCommerce/vc-platform#564]
Hi guys! I decided to test-drive how Shopify/liquid themes play with VirtoCommerce. And it seems they don't play well.

Here's a sample Shopify store I added my template to: https://drdrdr.myshopify.com/ Everything works just fine. Now I tried importing this same template to VirtoCommerce in two ways - via the Shopify import module and via manual theme upload/installation via admin site. This is what I get: 
![image](https://cloud.githubusercontent.com/assets/10373681/17205206/68b7e51a-54b2-11e6-8a1c-33216acecad9.png)

Apparently, the main reason is that VirtoCommerce doesn't seem to compile .scss and .scss.liquid files to css, as Chrome Dev mode shows:
![image](https://cloud.githubusercontent.com/assets/10373681/17205308/0dea33f8-54b3-11e6-8040-ba3d75d0c0ed.png)

Also, the import module failed to import quite a few scripts. While after manual installation, it's just a few scss.css files that are missing.

Why is that?

**Comment by tatarincev** [comment]
Can you send your theme to us for local test?

**Comment by amironoff** [comment]
I can't attach it here publicly, but I can email it to you. Where should I send it?

**Comment by tatarincev** [comment]
You can email you theme to support@virtocommerce.com

**Comment by amironoff** [comment]
Just emailed it (look for 'Shopify template that VC won't import')

**Comment by tatarincev** [comment]
Was a some  incompatibility bug in main.scss.liquid file with used in VC storefront NET liquid and MCSS parser components.
And I found some issue with files resolving inconsistencies with Shopify rules. But it will be fixed in next storefront releases.

And other important notice. All links in native shopify themes work only when it run in host web application (testsite.com, my-site.my.com etc)
to start work on application level such as (testsite.com/mystore or my-site.my.com/mystore) you should add to each link in theme "| absolute_url" filter
Example:
 <a href="{{ '/account' | absolute_url }}">{{ customer.first_name }}</a>
