### ISSUE TITLE
create wireframe

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-platform#591]

**Comment by eMazeika** [comment]
wireframe http://1hjd50.axshare.com/#p=main_menu&hi=1

**Comment by Woland2k** [comment]
Subscription list should allow filtering by status, I want to be able to see all active, not active, expired, about to expire, just expired, cancelled subscriptions or subscriptions that have some issues (payment not processed, no payment defined).

Why is price part of payment plan? Price should be associated with a variation not plan. Rename "Payment Plan" to "Payment Schedule", i believe it still needs to be visible only if product is marked as "recurring" otherwise it will be confusing.
