### ISSUE TITLE
Migrate platform to .net core

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#617]
This will contain compilation of documents in relation to migrating to .net core

**Storefront Issues** 
1. Migrate OWIN implementation
   **JWT - token based authentication in core**
   http://andrewlock.net/a-look-behind-the-jwt-bearer-authentication-middleware-in-asp-net-core/
2. PagedList nuget is not compiled for .net core and there is no implementation

**Comment by Skrypt** [comment]
Here is @joeaudette pager implemented with tag helpers : 
https://github.com/joeaudette/cloudscribe.Web.Pagination

And I think there is also this one : 
https://github.com/sgjsakura/AspNetCore

But I'm sure you guys already figured it out 😄

**Comment by Woland2k** [comment]
Thanks for the links @Skrypt, we are considering removing dependencies on Pagelist, not sure we need such complex base class.

**Comment by jamalkaksouri** [comment]
Good Job, .net core is **extensible** and **modularity** platform

**Comment by ASADeveloper** [comment]
Although I'm very skeptical that this could ever be done, I'm curious about it. Is there any progress on this issue?
I see that it is on the roadmap of 2017, but it looks like nothing has been done about it, yet. If this is correct, I suggest putting this on the roadmap of 2018.
But I hope I'm wrong. Because you are one of the few e-commerce solutions that have reached our company's short-list candidates at the functional level.

**Comment by IgorisB** [comment]
@ASADeveloper Our goal is to start this year. Of course it is long term Epic feature. And it is not yet moved to the implementation stage. However it is open for analysis and discussion.

**Comment by dodyg** [comment]
I think the biggest dependency will be the readiness of EF Core.

**Comment by ultimatemm** [comment]
Hi ,
When will you finish to convert .NET Core version?

**Comment by ASADeveloper** [comment]
I don't think this could be 'converted' to .net core. It is more like re-programming the features in .NET Core.
And unfortunatly it probably going to fail at first, like most others. Don't get me wrong, I'm not questioning the potential and capabilities of the contributers. It's more about the whole .NET Core marketing strategy that gives the programmers the idea that it is something from the outside of the galaxy. Well, it is not... Almost all you see in .NET Core is already done in other languagues and frameworks. Put the good ideas in Python, Ruby and Java and current .NET together and you have the new .NET Core.
In my opnion this marketing strategy have negative effect on the confidence of the experienced developers. That could effect the project.

We have evaluated Virtocommerce as a replacement for our reseller portals (a few hunderds), but eventually we doubted about how it is going to survive the new frameworks and technologies.

I guess we just have to wait and see if/when/how this is migrated to the new framework and technologies.

**Comment by Skrypt** [comment]
I've successfully compiled VirtoCommerce.Storefront on a Mac but it would require some minor fixes to make it work with Mono. There's also the fact that with .NET Standard 2.0 almost all libraries from the legacy framework is now included in .NET Core. So, the most complex part is about finding alternatives to the third party libs that have been included in VirtoCommerce. Hopefully the Storefront has only few of them. So, I think that migrating to .NET Core for the Storefront part will be just a migration of some code because it already uses the principle of OWIN and registering services on app startup. I might be wrong but that's my first guess. I'm not too much worried at this point, running Virto on .NET 4.6.1 is fast enough. 

The main advantage of using .NET Core would be for having better response time from server side. But, then maybe only parts of Virto could be migrated to .NET Core ... think micro-services ... Web API... I think that for Storefront it could also gain some perf but like I said, you are also bound to the client side tech you are using and the speed optimizations you will make with those. It's all about finding a great balance. Lucene queries on .NET Core will be that much faster? Caching will be that much faster? ... 

I think, that for me the advantages of using .NET Core is mainly about having at last the opportunity to use docker containers and also develop C# on linux and/or Mac. Not anymore bound to Windows. Which makes this easier for content integrators/designers that are all on Mac these days.

**Comment by Woland2k** [comment]
@Skrypt awesome! I agree that Docker and ability to natively run on Mac are the main reasons. That is the reason to wait for .NET Standard 2.0.

**Comment by dodyg** [comment]
I think if .NET Core 2.0 supports EF6, it will go a long way to help the port (https://github.com/aspnet/EntityFramework6/issues/271)

**Comment by zhangpeng-kooboo** [comment]
Hi @tatarincev  I saw you are working on 'https://github.com/VirtoCommerce/vc-platform-core' already 👍, is there a roadmap you could share?

**Comment by tatarincev** [comment]
Here it is. 
https://github.com/VirtoCommerce/vc-platform-core/blob/master/README.md
True only without concrete estimates, but I hope it will be ready in month or earlier.

**Comment by tatarincev** [comment]
The platform on .NET Core 2.2 has been released [3.0.0-rc.2](https://github.com/VirtoCommerce/vc-platform/releases/tag/3.0.0-rc.2)
