### ISSUE TITLE
"Object reference not set to an instance of an object." in CategoryBrowsingService.SearchCategories

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-platform#627]
can't start storefront on my localhost:

![image](https://cloud.githubusercontent.com/assets/5801549/18903569/9803eb8a-8562-11e6-8bbb-e4453a0120b9.png)

**Comment by Woland2k** [comment]
Fixed in this commit: https://github.com/VirtoCommerce/vc-module-search-api/commit/5d83fdef2812d05c93f5862798b9a891c3038d1c

**Comment by Skrypt** [comment]
Having the same problem but found out that the problem was that when I migrated the data in Virto I used NEWID() for Id guids in tables. Somehow Lucene does'nt like it ; so I changed it to LOWER(REPLACE(NEWID(),'-', '')) and now I get results from Lucene from the web API.

I'm still testing it and will report if I find anything else about this.

**Comment by Skrypt** [comment]
From what I understand now is that this error happens at any time that the Web API is returning an error. So your error could be totally different than mine.

**Comment by eMazeika** [comment]
i was using fresh DB and 2.12 sample data. Was doing "Rebuild index" without any luck and only this fix did the trick - storefront opens again
