### ISSUE TITLE
RTL localization enhancement

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#743]
ui-grid - add globally for actions column '{ name: 'actions', displayName: '', enableColumnResizing: false, enableSorting: false, width: 30, cellTemplate: 'list-actions.cell.html', pinnedRight:isRTL , pinnedLeft: !isRTL }'

Change datpicker and date format to persian calendar (jalali) has specific requirement and different from Gregorian calandar

**Comment by alireza-salehi** [comment]
for ui-grid correct RTL support following configurations are needed:

1. 'dir' attribute on grid tag with 'rtl' value in RTL mode. for example: 
` <div ui-grid="gridOptions" dir="rtl" ui-grid-auto-resize ui-grid-save-state ui-grid-selection ui-grid-resize-columns ui-grid-move-columns ui-grid-pinning ui-grid-height></div>`
2. pinned columns must pin to right instead of left. for example:
'{ name: 'actions', displayName: '', enableColumnResizing: false, enableSorting: false, width: 30, cellTemplate: 'list-actions.cell.html', pinnedRight: true}' 
'pinnedLeft' must be removed (or set to false when both present) from column configuration in RTL mode.

![rtl](https://cloud.githubusercontent.com/assets/9166109/23330304/cca2df86-fb5f-11e6-8842-abe8efdbe2b3.png)
![ltr](https://cloud.githubusercontent.com/assets/9166109/23330309/dffdc0f0-fb5f-11e6-84fd-ee19c91b8d1b.png)

**Comment by asvishnyakov** [comment]
\+ Now you need to reload page to correct apply RTL changes to UI, while translate for languages applied immediately

**Comment by alireza-salehi** [comment]
very simple to reload:
VirtoCommerce.Platform.Web\Scripts\app\userProfile\blades\userProfile.js
you need to edit setLanguage like this:
`    $scope.setLanguage = function () {
        $translate.use(blade.currentLanguage);
        location.reload();
    };`

**Comment by asvishnyakov** [comment]
@alireza-salehi thank you, but I know it :) it's just note to not forget it when we'll fix RTL support

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-85
