### ISSUE TITLE
Performance Issue when use search by keyword in Organization & Contacts 

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#824]
We uploaded ~65000 contacts and detected the performance issue when use search by keyword in Organization & Contacts.

We use 
+ platform 2.13.0 
+ latest VC Modules 
+ custom extension above Organization & Contacts module.

DB plan is S1 Standard (20 DTUs).
Web site plan is S2.

Now it takes ~ 20 sec and 80-100% DTU. See attached screenshots.

![default](https://cloud.githubusercontent.com/assets/7639413/24422251/265b88d2-13f9-11e7-81c6-b0f3d433b8b6.png)

Could you please advise me how to fix this issue?

**Comment by artem-dudarev** [comment]
Here is the code that implements the keyword search:
`m.Name.Contains(criteria.Keyword) || m.Emails.Any(e => e.Address.Contains(criteria.Keyword))`
In your case, this results in 1.5 million of read operations on the SQL server for each search request.

The best solution is to write a new implementation of `IMemberSearchService` which would use a search provider for full text search.

There is an alternative solution if you need to search only for the full email address.
You can override `CommerceMembersServiceImpl.GetQueryPredicate` method and use Equals instead of Contains. This should be faster because there is an index on `Email.Address` field in the database.

**Comment by OlegoO** [comment]
@tatarincev and @artem-dudarev 
When you can resolve this issue?

**Comment by IgorisB** [comment]
@aartiomov is this considered in #909 ?

**Comment by artem-dudarev** [comment]
Indexed search is implementd in VirtoCommerce.Customer v2.14.1
