### ISSUE TITLE
Core module:  Enhancing debugging for all domain types

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#932]
https://msdn.microsoft.com/en-us/library/ms228992(v=vs.110).aspx
or by other better solution

**Comment by asvishnyakov** [comment]
Research result:
- Do not override ToString() method for debugging reasons because it may affect other code and we have better solution with `System.Diagnostics.Debug` assembly.
- Do not set `Debugger​Browsable​Attribute` to `Never`. There is no type members what we may want to hide.
- Set `Debugger​Browsable​Attribute` to `RootHidden`, if we want to include collection items as class members. There is also no types where we want to use that, I think.
- `Debugger​Display​Attribute` is most usable to format type member, for example -`PropertyValue: "Brand: Samsung"` or `EditorialReview: "Language: en, Type: FullReview"`
- `Debugger​Type​Proxy​Attribute` is most powerful of this classes. It allow us to *rewrite* class presentation on debugging. For example, we may show `CatalogProduct` property value inside `Property` type member although `Properties` and `PropertyValues` is different collections.

**Comment by asvishnyakov** [comment]
@tatarincev Need your opinion

**Comment by tatarincev** [comment]
`DebuggerDisplay` looking as best way for this.
We have some it usage examples in `Virtocommerce.Domain` project in `VirtoCommerce.Domain.Search` namespace,
