### ISSUE TITLE
Outlines for linked categories

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#966]
Customer question:

Ok, am i right in thinking though that the linked category itself won't be accessible directly. ie if I have a virtual catalog with a linked category at the top level with an seo url of "mycat" it isn't acccesible on "~/mycat" but if it was place inside a common category of "mycat2" all of the content of mycat would be visible on ~/mycat2

Thats great, I just wanted to make sure I'd understood correctly as I've had to tweak a few bits at storefront end to make sure the linked category is not reference. eg on a product page for a product that was in a linked category the breadcrumb links back to the linked category not the common category.

I had it set to Collapsed. The url's are correct (and behave as described in the admin) however in the storefront product controller I can see that on WorkContext.CurrentProduct the outline always contains the ids for category/linkedcategory/product and WorkContext.CurrentProduct.Categoryid is for the linkedcategory (ie its actual common category) . The categoryid is used to set the current category which is displayed in the breadcrumb however this is the linked category and from a different catalog.

**Comment by artem-dudarev** [comment]
Linked (physical) category is not accessible on storefront only if SEO links type is set to Collapsed, which means "hide linked category from URL".
At the same time, SEO links type doesn't affect actual catalog structure. Products belong to physical categories, that's why a product still has a linked category as CategoryId and has linked category in the outline.

As for breadcrumbs, probably there is an an error - we'll check it.
